default:
 tags:
    - gitlab-k8-kkm
stages:
 - aws-ecr-registry

gitlab-build:
 stage: aws-ecr-registry
 variables:
    AWS_DEFAULT_REGION: eu-west-2
    CI_REGISTRY_IMAGE: 707212052238.dkr.ecr.eu-west-2.amazonaws.com/devsecops
 image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
 script:
    -  mkdir -p /kaniko/.docker
    -  echo "{\"credsStore\":\"ecr-login\"}" > /kaniko/.docker/config.json
    -  /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
